spring:
  application:
    name: filmorate
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate;NON_KEYWORDS=user;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_schema: public
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

logging:
  level:
    org.zalando.logbook: info